Try to wait for browser

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -67,7 +67,21 @@ jobs:
             -   name: Install certificates
                 run: symfony server:ca:install
             -   name: Run Chrome headless
-                run: google-chrome-stable --enable-automation --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --allow-insecure-localhost --disable-translate --disable-extensions --no-sandbox --enable-features=Metal --headless --remote-debugging-port=9222 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' http://127.0.0.1 > /dev/null 2>&1 &
+                run: |
+                    google-chrome-stable --enable-automation --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --allow-insecure-localhost --disable-translate --disable-extensions --no-sandbox --enable-features=Metal --headless --remote-debugging-port=9222 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' http://127.0.0.1 > /dev/null 2>&1 &
+                    x=1
+                    while [[ $x -le 15 && ! $code -eq "200" ]]
+                    do
+                      code=$(curl -s -o /dev/null -I -w "%{http_code}" http://127.0.0.1:9222/json/version)
+                      sleep 1
+                      x=$(( $x + 1 ))
+                    done
+
+                    if [ ! $code -eq "200"  ]
+                    then
+                      echo "Could not start Chrome browser"
+                      exit 1
+                    fi
             -   name: Run webserver
                 run: (cd tests/Application && symfony server:start --port=8080 --dir=public --daemon)
             -   name: Run behat with javascript
